### ISSUE TITLE
Chapter 4 README.md typo?

### ISSUE THREAD

**Issue by remyzandwijk** [geerlingguy/kubernetes-101#13]
@geerlingguy, I suspect a typo in the k8s-manifests/README.md of chapter 4.

Shouldn't the line:
`kubectl logs -n -f drupal -l app=drupal`

read:
`kubectl logs -f -n drupal -l app=drupal` ?

Thanks!

**Comment by geerlingguy** [comment]
Oops, yes! I will get that fixed soon. Thanks for catching that!
