### ISSUE TITLE
Episode 3 - expose port with docker-minikube

### ISSUE THREAD

**Issue by nidomiro** [geerlingguy/kubernetes-101#17]
First of all thanks for your work :)
Finally I'm learning kubernetes after several failed attempts ;)

I'm referencing: https://github.com/geerlingguy/kubernetes-101/tree/master/episode-03#exposing-the-hello-go-app

My minikube used docker to startup kubernetes and therefore the port-bindings do not work as expected.
The Solution is to use `minikube service hello-go --url` to get the url to paste into the browser.

**Comment by geerlingguy** [comment]
I'll take a second look at this and see if I can make the wording a little clearer especially if you're not using a VM for it like I am.

**Comment by kientran** [comment]
Yep, ran into this issue also!   Something about minikube in docker I suppose
