### ISSUE TITLE
Got drupal pod with pending status in Episode 05

### ISSUE THREAD

**Issue by Kiollpt** [geerlingguy/kubernetes-101#30]
I tried two times for building it up, but I still can not figure out how I can fix it.

```
NAME                                                 READY   STATUS    RESTARTS   AGE
nfs-client-provisioner-1626519840-5d45c6b567-hf9tb   1/1     Running   0          13m
```

```
NAME                      READY   STATUS    RESTARTS   AGE
drupal-79f84f8697-rmmzw   0/1     Pending   0          10m
mariadb-7d4bd4bf8-2j5cn   1/1     Running   0          15m
```

And I  used the `describe`  command to the drupal then I got two events below.
It seemed like it stuck there.

```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  5m9s  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  5m8s  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  ```

**Comment by geerlingguy** [comment]
`unbound immediate PersistentVolumeClaims` indicates there's an issue getting PVCs, which may mean NFS is not working correctly. Make sure the NFS server is running and reachable, and make sure Kubernetes can see it okay.

**Comment by Kiollpt** [comment]
Hello @geerlingguy 

My k8s version is `1.21`,  then I changed the original helm chart to this 
```
$ helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
$ helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
    --set nfs.server=x.x.x.x \
    --set nfs.path=/exported/path
 ```

Now, everything works well.  I think it is related to #28

 How can I debug by log to know the helm chart that caused this problem?

**Comment by geerlingguy** [comment]
Thanks for posting back—it could just be an updated helm chart—the logs for helm stuff can get tedious as you need to check the helm release status (https://helm.sh/docs/helm/helm_status/) and all the stuff inside (https://polarsquad.com/blog/check-your-helm-deployments).
