### ISSUE TITLE
Chapter 3: Exposing deployment does not seem to work as described

### ISSUE THREAD

**Issue by HGS9761** [geerlingguy/kubernetes-101#40]
Hi,

I have followed the sequence of statements in Chapter 3.
See below

`$ kubectl get pods,svc -A
NAMESPACE     NAME                                   READY   STATUS    RESTARTS      AGE
default       pod/hello-go-7445c6c654-5wrrc          1/1     Running   0             4m48s
kube-system   pod/coredns-6d4b75cb6d-5vwg6           1/1     Running   0             19m
kube-system   pod/etcd-minikube                      1/1     Running   0             20m
kube-system   pod/kube-apiserver-minikube            1/1     Running   0             20m
kube-system   pod/kube-controller-manager-minikube   1/1     Running   0             20m
kube-system   pod/kube-proxy-dzjhv                   1/1     Running   0             19m
kube-system   pod/kube-scheduler-minikube            1/1     Running   0             20m
kube-system   pod/storage-provisioner                1/1     Running   1 (19m ago)   20m

NAMESPACE     NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       service/hello-go     NodePort    10.99.245.118   <none>        80:32477/TCP             3m51s
default       service/kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP                  20m
kube-system   service/kube-dns     ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP   20m
`

According to page 25 the service should be accessible via ip address 10.99.245.118  and port 32477.
However nothing is available at port 32477.

I also tried :
`kubectl expose deployment hello-go --port=80 --target-port=8180 --type=NodePort --external-ip 112.14.19.151`
Of which the external-ip is the ip address of the host. That however does not make a difference

With `ss -an|grep LISTEN|grep ^tcp` nothing seems to listen at the port.

Regards Hans

**Comment by dstuartkelly** [comment]
Hi Hans,
Just finished episode-03 myself and didnt find an issue with this. I have been following the videos and the [README.md ](https://github.com/geerlingguy/kubernetes-101/blob/master/episode-03/README.md) and found the instructions there to be accurate.

`kubectl expose deployment hello-go --port=80 --target-port=8180 --type=NodePort`

From your outpt it looks like you are using minikube as per the videos, so hopefully you figured this out already.

Get your applications port from  `kubectl get service hello-go`
```
$ kubectl get service hello-go
NAME       TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
hello-go   NodePort   10.101.77.98   <none>        80:32621/TCP   159m
```

Get the IP Address from minikube using `minikube ip`

```
$ minikube ip
192.168.50.2
```
With the above outputs I access the application on http://192.168.50.2:32621
