### ISSUE TITLE
K8s 101 YT playlist has extra video

### ISSUE THREAD

**Issue by PresGas** [geerlingguy/kubernetes-101#8]
Wanted to let you know that there is an extra video in your K8s 101 playlist that I didn't think was intended to be there:

https://www.youtube.com/playlist?list=PL2_OBreMn7FoYmfx27iSwocotjiikS5BD

I have not clicked on it, but it looks to be from this YT user:
https://www.youtube.com/user/questort

Do you know this user?

**Comment by geerlingguy** [comment]
I have no idea how that happened, but I've removed that video from the playlist. Thanks for letting me know!
